### PR TITLE
Remove some tuple usage

### PR DESCRIPTION
**Pull request by spuun**
### WHAT is this pull request doing?
It's very annoying when tuples are nested in tuples and you need to do `value[0][1]`. This will change `BindingKey` and `QueueBinding` from `Tuple` to `struct`.

Interesting is that

```crystal
alias QueueBinding = Tuple(BindingKey, Exchange)
```
didn't force the order of the values based on type, see

https://github.com/cloudamqp/lavinmq/blob/0603aa921a37e5bb41ba803b78a77082f4375602/src/lavinmq/vhost.cr#L365-L372

where the orders in line 369 are swapped compared to `QueueBinding`

One problem with this refactoring is that `Hash#[](key)` isn't type, which means we don't get any compile time error when we access our binding hashes with the old value, so there's a risk i've missed change the type in one place or two.

### HOW can this pull request be tested?
Run specs

### CODE REVIEW

**Comment by spuun** [comment]
IMO we should avoid `Tuple` and `NamedTuple` everywhere.

**Comment by spuun** [comment]
I monkey patched `Hash` locally and didn't find anything related to this change.

**Comment by snichme** [comment]
This will conflict with https://github.com/cloudamqp/lavinmq/pull/786 but I like the approach of using a struct instead of an alias. How about I introduced the struct in mr PR instead?

**Review by carlhoerberg — APPROVED** [review]

**Comment by carlhoerberg** [comment]
> IMO we should avoid `Tuple` and `NamedTuple` everywhere.

Totally do not agree. In this case it makes sense, but there are definitely cases where Tuple or NamedTuples is the better option.

**Comment by spuun** [comment]
> > IMO we should avoid `Tuple` and `NamedTuple` everywhere.
> 
> Totally do not agree. In this case it makes sense, but there are definitely cases where Tuple or NamedTuples is the better option.

Well, I'm generalizing a bit. But I think that many uses of NamedTuple can be a struct instead.

**Comment by spuun** [comment]
> This will conflict with #786 but I like the approach of using a struct instead of an alias. How about I introduced the struct in mr PR instead?

@kickster97 and I wanted this in the mqtt branch, but I guess it's no rush. I think this can be done even better by changing some interfaces to require a `BindingKey` instead of constructing it everywhere like I did now.

**Comment by spuun** [comment]
Superseded by #786

**Comment by spuun** [comment]
Superseded by #786

**Pull request closed without merging**
