### PR TITLE
SystemD.notify_ready when starting as follower

### PR DESCRIPTION
**Pull request by viktorerlingsson**
### WHAT is this pull request doing?
Sends SystemD.notify_ready when starting LavinMQ as follower, so systemd knows the service has finished activating. 

### HOW can this pull request be tested?
Start LavinMQ as a service as a follower

### CODE REVIEW

**Comment by viktorerlingsson** [comment]
Maybe `SystemD.notify_ready` should be before syncing files instead (i.e. after `authenticate`)? Depends on how we want to look at it I guess

**Comment by carlhoerberg** [comment]
Yes, after auth i would say

**Review by kickster97 — APPROVED** [review]

**Comment by carlhoerberg** [comment]
Sync can be called multiple times. Put it on top of follow instead

**Comment by viktorerlingsson** [comment]
> Sync can be called multiple times. Put it on top of follow instead

Yeah, that's probably better 👍

**Pull request merged**
