### PR TITLE
Download original java-client code and apply patch

### PR DESCRIPTION
**Pull request by snichme**
### WHAT is this pull request doing?

Same as being done to rabbit-hole tests, clone original repo and apply patch to disable tests that LavinMQ doesn't support or makes no sense to LavinMQ

### HOW can this pull request be tested?

Check GHA

### CODE REVIEW

**Review by kickster97 — APPROVED** [review]
nice!

**Comment by snichme** [comment]
The check fails now because the `curl` command to download the patch points to `main` but the branch isn't merged. 
So it will work when merged

**Comment by dentarg** [comment]
> The check fails now because the `curl` command to download the patch points to `main` but the branch isn't merged.
> So it will work when merged

Why not apply the patch from the current branch? I guess this step isn't cloning the lavinmq repo and instead uses artifact from other build steps, but I think cloning the repo to get the patch is better, then you can patch the patch in PRs and see it working?

**Comment by dentarg** [comment]
Here's how you can checkout just a single file: https://github.com/84codes/actions/blob/78e025f017394020a4a7be07e53546ba33100235/.github/workflows/ruby-ci.yml#L93-L102

**Comment by snichme** [comment]
@dentarg great tips, fixed that now

**Pull request merged**
