### PR TITLE
Use Log#emit and Log::Metadata

### PR DESCRIPTION
**Pull request by carlhoerberg**
Saves Log instances and uses Metadata instead, somewhat repetitive but the "native" way.

### CODE REVIEW

**Comment by baelter** [comment]
Can't we wrap this with our own `Log`, something like 
```crystal
class LavinMQ::Log < ::Log
  property metadata
  def debug
     msg = yield
     super.debug &.emit msg, metadata
  end
  ...
end

Log = LavinMQ::Log.for(self)
Log.metadata = ...
Log.debug { "yada" }
```
?

**Review by spuun — COMMENTED** [review]
Maybe the `EntityLog` in #502 is over-engineered with its expand methods and stuff should be more explicit, but i think using a Struct to wrap the Log instance and @metadata is nice so you can use the same syntax?

**Comment by spuun** [comment]
> Can't we wrap this with our own `Log`, something like
> 
> ```crystal
> class LavinMQ::Log < ::Log
>   property metadata
>   def debug
>      msg = yield
>      super.debug &.emit msg, metadata
>   end
>   ...
> end
> 
> Log = LavinMQ::Log.for(self)
> Log.metadata = ...
> Log.debug { "yada" }
> ```
> 
> ?
The EntityLog here does that:
https://github.com/cloudamqp/lavinmq/blob/logging-sources/src/lavinmq/logging.cr

**Comment by carlhoerberg** [comment]
Getting rid of `@log` that we might think be a memory leak. And doesn't do any monkey patching of anything, uses the "native" way of logging metadata with `Log`.

**Pull request merged**
