### PR TITLE
Abstract client/channel/consumer

### PR DESCRIPTION
**Pull request by spuun**
### WHAT is this pull request doing?

This will abstract Client/Channel/Consumer so we can implement different types of these entities. The current implementations of each entitiy is moved to the LavinMQ::AMQP namespace.

This abstraction should enable us to implement other protocols.

### HOW can this pull request be tested?
Run specs

### CODE REVIEW

**Comment by spuun** [comment]
I also refactored `Reporter` since it access instance variables. I'll probably break this out to a PR to this PR.

**Comment by spuun** [comment]
I think i'd like to move src/lavinmq/client/amqp/* to src/lavinmq/amqp/* and also include the queue implementations here since they are tied to `AMQP::Consumers`, so make `LavinMQ::AMQP::Queue` and `LavinMQ::AMQP::StreamQueue` and such... Not sure yet.

**Comment by spuun** [comment]
I'll revisit this at some point. Probably starting over.

**Comment by kickster97** [comment]
> I think i'd like to move src/lavinmq/client/amqp/* to src/lavinmq/amqp/* and also include the queue implementations here since they are tied to `AMQP::Consumers`, so make `LavinMQ::AMQP::Queue` and `LavinMQ::AMQP::StreamQueue` and such... Not sure yet.

Makes it easier to introduce other protocols so we don't have to mix e.g. amqp queues and mqtt sessions.. But i'm wondering: should we move **everything AMQP** to under the AMQP namespace? exchanges? etc..

**Pull request closed without merging**
