### PR TITLE
only consider MIN_ISR requirements if listeners are started

### LINKED ISSUE #727: Be able to start a new cluster with min_isr > 0
Currently can't start a new cluster with min_isr > 0 because the writes requires nodes, but the server hasn't started its listeners yet so no followers can connect, catch 22.

### PR DESCRIPTION
**Pull request by viktorerlingsson**
### WHAT is this pull request doing?
Ignores MIN_ISR requirements until listener has been started. Fixes #727 

### HOW can this pull request be tested?
Specs? Manual steps? Please fill me in.

### CODE REVIEW

**Comment by viktorerlingsson** [comment]
This seems to work for starting with `min_isr > 0`. WDYT @carlhoerberg ?

**Comment by carlhoerberg** [comment]
I'm just wondering if we should have min_isr at all,  Postgres doesnt, Kafka only doesnt ack publishes when min isr isnt fulfilled. Maybe we should do the same? Only not confirm publishes? 

But at least this doesnt brakes the "guarantee", if another server with the exact same data dir starts they would end up with the same data anyway.

**Comment by viktorerlingsson** [comment]
> I'm just wondering if we should have min_isr at all, Postgres doesnt, Kafka only doesnt ack publishes when min isr isnt fulfilled. Maybe we should do the same? Only not confirm publishes?

Hmm, yeah, I think that makes sense! 

> But at least this doesnt brakes the "guarantee", if another server with the exact same data dir starts they would end up with the same data anyway.

👍

**Comment by carlhoerberg** [comment]
But probably have to be in combination with storing metadata/definitions in etcd.

**Comment by carlhoerberg** [comment]
Fixed in #797

**Pull request closed without merging**
