### PR TITLE
Replication lag improvement

### PR DESCRIPTION
**Pull request by spuun**
### WHAT is this pull request doing?

Before this we only counted data written to the follower socket as lag, we didn't count the data in the "action queue" of the follower.

This will change so we count data written to the action queue.

### HOW can this pull request be tested?

Run follower specs

### CODE REVIEW

**Comment by kickster97** [comment]
hmm @dentarg, cla assistant skipped on my pr [here](https://github.com/cloudamqp/lavinmq/pull/613), but not here...

**Comment by dentarg** [comment]
@kickster97 Hmm, I wonder if skipping for `COLLABORATOR` too would help, reading https://stackoverflow.com/questions/63188674/github-actions-detect-author-association it sounds like it. I can experiment some.

**Comment by dentarg** [comment]
I think (hope) the CLA workflow behaves better now going forward. Closing/re-opening didn't really work as I expected, the workflow only ran on the close event: https://github.com/cloudamqp/lavinmq/actions/workflows/cla.yml?query=branch%3Areplication-lag-improvement – I unlocked this PR with the GitHub CLI and also created https://github.com/cloudamqp/lavinmq/pull/654

**Comment by spuun** [comment]
This will also count all data that needs to be sent as lag, not only "message data" (i.e. it counts filename length etc too).

**Comment by spuun** [comment]
> This will also count all data that needs to be sent as lag, not only "message data" (i.e. it counts filename length etc too).

Maybe it should be changed to only count message data.

**Review by kickster97 — APPROVED** [review]

**Comment by kickster97** [comment]
> > This will also count all data that needs to be sent as lag, not only "message data" (i.e. it counts filename length etc too).
> 
> Maybe it should be changed to only count message data.

Is it not more accurate if we count all data? Why would we only want to count message data?

**Pull request merged**
